version: "3.2"
services:
  rabbitmq:
    build:
      context: ./app/infra/rabbitmq
      
    environment:
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
      - RABBITMQ_READ_EMAIL_QUEUE=$RABBITMQ_READ_EMAIL_QUEUE
      
    ports:
      - 5672:5672
      - 15672:15672

    volumes:
      - ./app/infra/rabbitmq/data:/var/lib/rabbitmq
 