site_name: Signature Management Backend
repo_url: https://gitlab.com/jrsf68/signature-management-backend
repo_name: jrsf68/signature-management-backend
repo_uri: 
theme:
  name: material
  language: pt-BR
