FROM rabbitmq:3-management

ADD rabbitmq.conf /etc/rabbitmq/conf.d/
ADD definitions.json /etc/rabbitmq/conf.d/

# ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq

# ADD init.sh /
# ADD config_rabbit.sh /

# RUN chmod +x /init.sh /config_rabbit.sh

# CMD ["/init.sh"]
 