name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Copia o projeto
        uses: actions/checkout@v3.5.2

      - name: Roda outro comando!
        run: echo $(ls)