name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    steps:
=======
>>>>>>> a1270a8115517b2e930e4ae8374c6ebf2a2457b9
      - name: Roda um comando!
        run: echo $(pwd)

      - name: Roda outro comando!
        run: echo $(ls)